### ISSUE TITLE
As a user, I want to be able to search and order products so that I don't have to leave my house to get them.

### ISSUE THREAD

**Issue by DNTM2802** [92963-93080-93456-93019/cito-deliveries-management#10]
**Acceptance Criteria**
- [x] Given a search bar and a list of products to be fetched in the backend, when a user searches for the name of the product or uses a filter, a request is made, and the products of the response are presented in the UI with the respective order.
- [ ] Given a list of products and the amount of each one, along with the user's delivery data (including the Location), when the user makes a purchase then it is submitted to the backend to process the purchase. On the backend, the purchase is transformed into an order, ready to be attributed to a rider, to be used to show statistical data to the manager, or to be shown to the client.

**Definition of Done**
- [ ] Unit test passed
- [ ] Functional tests passed
- [ ] Code reviewed
- [ ] Product owner accepts the User Story

**Comment by l-sousa** [comment]
Done on other repositories.
