### ISSUE TITLE
As a user, I want to check the state of my order at any time, in order for me to know that the delivery is indeed on it's way and to be aware of it's arrival moment.

### ISSUE THREAD

**Issue by DNTM2802** [92963-93080-93456-93019/cito-deliveries-management#12]
**Description**
As a user, I want to check the state of my order at any time, such as if the rider has already picked up the meds, is on his way, or if he's at my door already, in order for me to know that the delivery is indeed on its way and to be aware of its arrival moment.

**Acceptance Criteria**
- [ ] Given an order, when the user requests its state, then one of the standard states or one of the store's specific states is returned.

**Definition of Done**
- [ ] Unit test passed
- [ ] Functional tests passed
- [ ] Code reviewed
- [ ] Product owner accepts the User Story

**Comment by l-sousa** [comment]
Done on other repositories.
