### ISSUE TITLE
As a store manager, I want to be able to register my products on the platform by category, so I can have my showcase as I want and be able to increase my sales.

### ISSUE THREAD

**Issue by DNTM2802** [92963-93080-93456-93019/cito-deliveries-management#9]
**Acceptance Criteria**
- [x] It should be possible to register a product's name, price, photo and description.
- [ ] Given a list of categories and a list of products by category, when the manager submits them to the platform, then they are loaded in the database and are available for the client.
- [ ] Given a product or a category of products, when the manager deletes them, then they are removed from the database and are no longer available to the clients.
- [ ] Given a category, when I as a manager want to edit it, I can change its name.
- [ ] Given a product, when I as a manager want to edit it, I can change all its attributes.

**Definition of Done**
- [ ] Unit tests passed
- [ ] Functional tests passed
- [ ] Code reviewed
- [ ] Product owner accepts the User Story

**Comment by l-sousa** [comment]
Done on other repositories.
